### ISSUE TITLE
[Bug] db field name is keywords will raise `AttributeError: 'function' object has no attribute 'translate'`

### ISSUE THREAD

**Issue by potoo0** [ThibTrip/pangres#34]
test script:
```python
import pandas as pd
from pangres import upsert
from sqlalchemy import create_engine

conn_str = 'mysql+pymysql://root:root@localhost:3306/testdb?charset=utf8'
engine = create_engine(conn_str)
table = 'df'

# values is the keywords of mysql
df = pd.DataFrame(
    {'a': range(5, 9), 'values': range(5, 9)}
)
df.index.name = 'idx'

# pandas to_sql, working
df.to_sql(table, engine, if_exists='append')

# pangres upsert, raise `AttributeError: 'function' object has no attribute 'translate'`
upsert(
    engine=engine,
    df=df,
    table_name=table + '_pangres',
    if_row_exists='update'
)
```

Traceback:
```
Traceback (most recent call last):
  File "e:\Template\testpandas.py", line 18, in <module>
    upsert(
  File "d:\miniconda3\lib\site-packages\pangres\core.py", line 240, in upsert
    return pse.upsert(if_row_exists=if_row_exists, chunksize=chunksize, yield_chunks=yield_chunks)
  File "d:\miniconda3\lib\site-packages\pangres\helpers.py", line 504, in upsert
    upsert_func(engine=self.engine,
  File "d:\miniconda3\lib\site-packages\pangres\upsert.py", line 112, in mysql_upsert
    return connection.execute(upsert)
  File "d:\miniconda3\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "d:\miniconda3\lib\site-packages\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "d:\miniconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "d:\miniconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "d:\miniconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "d:\miniconda3\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "d:\miniconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "d:\miniconda3\lib\site-packages\sqlalchemy\engine\default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
  File "d:\miniconda3\lib\site-packages\pymysql\cursors.py", line 161, in execute
    query = self.mogrify(query, args)
  File "d:\miniconda3\lib\site-packages\pymysql\cursors.py", line 140, in mogrify
    query = query % self._escape_args(args, conn)
  File "d:\miniconda3\lib\site-packages\pymysql\cursors.py", line 120, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "d:\miniconda3\lib\site-packages\pymysql\cursors.py", line 120, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "d:\miniconda3\lib\site-packages\pymysql\connections.py", line 469, in literal
    return self.escape(obj, self.encoders)
  File "d:\miniconda3\lib\site-packages\pymysql\connections.py", line 462, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "d:\miniconda3\lib\site-packages\pymysql\converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "d:\miniconda3\lib\site-packages\pymysql\converters.py", line 123, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "d:\miniconda3\lib\site-packages\pymysql\converters.py", line 78, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'function' object has no attribute 'translate'
```

**Comment by ThibTrip** [comment]
Hi @potoo0 ! Thanks for the issue! I was very busy sorry :turtle: .

The column name **`values`** seems to cause problems with `sqlalchemy`. If you change the column name to anything else it shall work (I even tried it with accents and special characters).

I'll try to come up with a much simpler code to make an issue directly on sqlalchemy. In the meantime you can use the workaround described above :+1: !

**Comment by ThibTrip** [comment]
Okay it's fixed :+1: ! If there is anything else please let me know!

**Comment by potoo0** [comment]
thx, it works perfect
